/*
 * Copyright 2022 Linda project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.d1s.linda.testUtil

import dev.d1s.linda.domain.Identifiable
import dev.d1s.linda.domain.Redirect
import dev.d1s.linda.domain.ShortLink
import dev.d1s.linda.domain.alias.FriendlyAliases
import dev.d1s.linda.domain.availability.AvailabilityChange
import dev.d1s.linda.domain.utmParameter.UtmParameter
import dev.d1s.linda.domain.utmParameter.UtmParameterType
import dev.d1s.teabag.testing.constant.VALID_STUB
import java.time.Instant

const val TEST_URL = "https://d1s.dev/"

val shortLink = ShortLink(
    TEST_URL,
    VALID_STUB,
    false,
    null,
    mutableSetOf(),
    mutableSetOf()
).setAutoGeneratedValues()

val shortLinks = setOf(shortLink)

val redirect = Redirect(
    shortLink
).setAutoGeneratedValues()

val redirects = setOf(redirect)

val utmParameter = UtmParameter(
    UtmParameterType.CONTENT,
    VALID_STUB,
    false
).setAutoGeneratedValues()

val utmParameters = setOf(utmParameter)

val availabilityChange = AvailabilityChange(
    shortLink,
    null
).setAutoGeneratedValues()

val availabilityChanges = setOf(availabilityChange)

val friendlyAliases = FriendlyAliases(
    setOf(VALID_STUB),
    setOf(VALID_STUB)
)

val identifiableSet = setOf(
    object : Identifiable {
        override var id: String? = VALID_STUB
        override var creationTime = Instant.EPOCH
    } as Identifiable // ¯\_(ツ)_/¯ 'public' property exposes its 'local' type argument <no name provided>
)