package uno.d1s.linda.constant.mapping.api

const val REDIRECTS_BASE_MAPPING = "$API_BASE_MAPPING/redirects"
const val REDIRECTS_FIND_ALL_MAPPING = REDIRECTS_BASE_MAPPING
const val REDIRECTS_FIND_BY_ID_MAPPING = "$REDIRECTS_BASE_MAPPING/{identifier}"
const val REDIRECTS_FIND_ALL_BY_SHORT_LINK_MAPPING = "$REDIRECTS_BASE_MAPPING/$SHORT_LINKS_BASE_NAME/{identifier}"
const val REDIRECTS_REMOVE_MAPPING = "$REDIRECTS_BASE_MAPPING/{identifier}"
const val REDIRECTS_REMOVE_ALL_MAPPING = REDIRECTS_BASE_MAPPING
const val REDIRECTS_BULK_REMOVE_MAPPING = "$REDIRECTS_BASE_MAPPING/part"
const val REDIRECTS_REMOVE_ALL_BY_SHORT_LINK_MAPPING = "$REDIRECTS_BASE_MAPPING/$SHORT_LINKS_BASE_NAME/{identifier}"