package uno.d1s.linda.constant.mapping.api

const val SHORT_LINKS_BASE_NAME = "shortLinks"
const val SHORT_LINKS_BASE_MAPPING = "$API_BASE_MAPPING/$SHORT_LINKS_BASE_NAME"
const val SHORT_LINKS_FIND_ALL_MAPPING = SHORT_LINKS_BASE_MAPPING
const val SHORT_LINKS_FIND_MAPPING = "$SHORT_LINKS_BASE_MAPPING/{identifier}"
const val SHORT_LINKS_CREATE_MAPPING = SHORT_LINKS_BASE_MAPPING
const val SHORT_LINKS_REMOVE_MAPPING = "$SHORT_LINKS_BASE_MAPPING/{identifier}"
const val SHORT_LINKS_REMOVE_ALL_MAPPING = SHORT_LINKS_BASE_MAPPING
const val SHORT_LINKS_BULK_REMOVE_MAPPING = "$SHORT_LINKS_BASE_MAPPING/part"