/*
 * Copyright 2022 Linda project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.d1s.linda.service

import com.ninjasquad.springmockk.MockkBean
import dev.d1s.linda.configuration.properties.AvailabilityChecksConfigurationProperties
import dev.d1s.linda.constant.lp.SHORT_LINK_CREATED_GROUP
import dev.d1s.linda.constant.lp.SHORT_LINK_REMOVED_GROUP
import dev.d1s.linda.constant.lp.SHORT_LINK_UPDATED_GROUP
import dev.d1s.linda.entity.ShortLink
import dev.d1s.linda.entity.utmParameter.UtmParameterPurpose
import dev.d1s.linda.dto.shortLink.ShortLinkDto
import dev.d1s.linda.event.data.shortLink.CommonShortLinkEventData
import dev.d1s.linda.event.data.shortLink.ShortLinkUpdatedEventData
import dev.d1s.linda.exception.badRequest.impl.utmParameter.DefaultUtmParametersNotAllowedException
import dev.d1s.linda.exception.notFound.impl.ShortLinkNotFoundException
import dev.d1s.linda.repository.ShortLinkRepository
import dev.d1s.linda.service.impl.ShortLinkServiceImpl
import dev.d1s.linda.strategy.shortLink.byAlias
import dev.d1s.linda.strategy.shortLink.byId
import dev.d1s.linda.testUtil.*
import dev.d1s.lp.server.publisher.AsyncLongPollingEventPublisher
import dev.d1s.teabag.dto.DtoConverter
import dev.d1s.teabag.stdlib.collection.mapToMutableSet
import dev.d1s.teabag.testing.constant.INVALID_STUB
import dev.d1s.teabag.testing.constant.VALID_STUB
import io.mockk.verify
import io.mockk.verifyAll
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertDoesNotThrow
import org.junit.jupiter.api.assertThrows
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler
import org.springframework.test.context.ContextConfiguration
import strikt.api.expectThat
import strikt.assertions.*
import java.time.Duration
import java.time.Instant

@SpringBootTest
@ContextConfiguration(classes = [ShortLinkServiceImpl::class])
class ShortLinkServiceImplTest {

    @Autowired
    private lateinit var shortLinkServiceImpl: ShortLinkServiceImpl

    @MockkBean
    private lateinit var shortLinkRepository: ShortLinkRepository

    @MockkBean
    private lateinit var availabilityChangeService: AvailabilityChangeService

    @MockkBean
    private lateinit var availabilityChecksConfigurationProperties: AvailabilityChecksConfigurationProperties

    @MockkBean(relaxed = true)
    private lateinit var scheduler: ThreadPoolTaskScheduler

    @MockkBean
    private lateinit var shortLinkDtoConverter: DtoConverter<ShortLinkDto, ShortLink>

    @MockkBean(relaxed = true)
    private lateinit var publisher: AsyncLongPollingEventPublisher


    private val expiredShortLink = shortLink.copy()
        .setAutoGeneratedValues().apply {
            deleteAfter = Duration.ZERO
        }

    @BeforeEach
    fun setup() {
        shortLinkRepository.prepare()
        availabilityChangeService.prepare()
        availabilityChecksConfigurationProperties.prepare()
        shortLinkDtoConverter.prepare()
    }

    @Test
    fun `should find all short links`() {
        withStaticConverterFacadeMock(shortLinkDtoConverter) { converter ->
            converter.prepare()

            expectThat(
                shortLinkServiceImpl.findAll(true)
            ) isEqualTo (shortLinks to shortLinkDtoSet)

            verifyAll {
                shortLinkRepository.findAll()
                converter.convertToDtoSet(shortLinks)
            }
        }
    }

    @Test
    fun `should find short link by id`() {
        expectThat(
            shortLinkServiceImpl.find(byId(VALID_STUB), true)
        ) isEqualTo (shortLink to shortLinkDto)

        verifyAll {
            shortLinkRepository.findById(VALID_STUB)
            shortLinkDtoConverter.convertToDto(shortLink)
        }
    }

    @Test
    fun `should throw ShortLinkNotFoundException when finding by invalid id`() {
        assertThrows<ShortLinkNotFoundException> {
            shortLinkServiceImpl.find(byId(INVALID_STUB))
        }

        verify {
            shortLinkRepository.findById(INVALID_STUB)
        }
    }

    @Test
    fun `should find short link by alias`() {
        expectThat(
            shortLinkServiceImpl.find(byAlias(VALID_STUB), true)
        ) isEqualTo (shortLink to shortLinkDto)

        verifyAll {
            shortLinkRepository.findByAlias(VALID_STUB)
            shortLinkDtoConverter.convertToDto(shortLink)
        }
    }

    @Test
    fun `should throw ShortLinkNotFoundException when finding by invalid alias`() {
        assertThrows<ShortLinkNotFoundException> {
            shortLinkServiceImpl.find(byAlias(INVALID_STUB))
        }

        verify {
            shortLinkRepository.findByAlias(INVALID_STUB)
        }
    }

    @Test
    fun `should create short link`() {
        val testShortLink = shortLink.copy()
            .setAutoGeneratedValues()

        expectThat(
            shortLinkServiceImpl.create(testShortLink)
        ) isEqualTo (testShortLink to shortLinkDto)

        verifyAll {
            availabilityChecksConfigurationProperties.eagerAvailabilityCheck
            availabilityChangeService.checkAvailability(shortLink)
            shortLinkRepository.save(testShortLink)
            shortLinkDtoConverter.convertToDto(testShortLink)
            publisher.publish(
                SHORT_LINK_CREATED_GROUP,
                VALID_STUB,
                CommonShortLinkEventData(shortLinkDto)
            )

        }
    }

    @Test
    fun `should throw DefaultUtmParametersNotAllowedException`() {
        val testShortLink = shortLink.copy().apply {
            allowUtmParameters = false
            defaultUtmParameters = utmParameters.toMutableSet()
        }

        assertThrows<DefaultUtmParametersNotAllowedException> {
            shortLinkServiceImpl.create(testShortLink)
        }
    }

    @Test
    fun `should update short link`() {
        val anotherShortLink = shortLink.copy().apply {
            alias = INVALID_STUB
        }

        val (updatedRedirect, dto) = shortLinkServiceImpl.update(
            VALID_STUB,
            anotherShortLink
        )

        expectThat(
            updatedRedirect.alias
        ) isEqualTo INVALID_STUB

        verifyAll {
            // verification fails without this
            shortLinkRepository.findById(VALID_STUB)

            shortLinkRepository.save(updatedRedirect)
            shortLinkDtoConverter.convertToDto(updatedRedirect)
            publisher.publish(
                SHORT_LINK_UPDATED_GROUP,
                VALID_STUB,
                ShortLinkUpdatedEventData(
                    shortLinkDto,
                    dto!!
                )
            )
        }
    }

    @Test
    fun `should assign utm parameters to short link`() {
        val testUtmParameters = utmParameters.mapToMutableSet {
            it.copy()
        }

        val testShortLink = shortLink.copy()
        val associatedShortLink = shortLink.copy().apply {
            defaultUtmParameters = testUtmParameters
            allowedUtmParameters = testUtmParameters
        }

        setOf(
            UtmParameterPurpose.DEFAULT,
            UtmParameterPurpose.ALLOWED
        ).forEach {
            shortLinkServiceImpl.assignUtmParameters(
                testShortLink,
                associatedShortLink,
                it
            )
        }

        val assignedDefaultUtmParameters = testShortLink.defaultUtmParameters
        val assignedAllowedUtmParameters = testShortLink.allowedUtmParameters

        setOf(
            assignedDefaultUtmParameters,
            assignedAllowedUtmParameters
        ).forEach {
            expectThat(it).containsExactly(
                testUtmParameters
            )
        }

        testUtmParameters.forEach {
            expectThat(
                it.defaultForShortLinks
            ).contains(testShortLink)

            expectThat(
                it.allowedForShortLinks
            ).contains(testShortLink)
        }
    }

    @Test
    fun `should remove short link by id`() {
        assertDoesNotThrow {
            shortLinkServiceImpl.removeById(VALID_STUB)
        }

        verify {
            shortLinkRepository.delete(shortLink)
            publisher.publish(
                SHORT_LINK_REMOVED_GROUP,
                VALID_STUB,
                CommonShortLinkEventData(
                    shortLinkDto
                )
            )
        }
    }

    @Test
    fun `should return valid answer whether the given alias exists or not`() {
        expectThat(
            shortLinkServiceImpl.doesAliasExist(VALID_STUB)
        ).isTrue()

        expectThat(
            shortLinkServiceImpl.doesAliasExist(INVALID_STUB)
        ).isFalse()
    }

    @Test
    fun `should return valid answer whether the short link is expired or not`() {
        expectThat(
            shortLinkServiceImpl.isExpired(shortLink)
        ).isFalse()

        expectThat(
            shortLinkServiceImpl.isExpired(expiredShortLink)
        ).isTrue()
    }

    @Test
    fun `should schedule expired short link for deletion`() {
        assertDoesNotThrow {
            shortLinkServiceImpl.scheduleForDeletion(expiredShortLink)
        }

        verify {
            scheduler.schedule(any(), any<Instant>())
        }
    }

    @Test
    fun `should NOT schedule expired short link for deletion`() {
        assertDoesNotThrow {
            shortLinkServiceImpl.scheduleForDeletion(shortLink)
        }

        verify(exactly = 0) {
            scheduler.schedule(any(), any<Instant>())
        }
    }

    @Test
    fun `should schedule all ephemeral short links for deletion`() {
        assertDoesNotThrow {
            shortLinkServiceImpl.scheduleAllEphemeralShortLinksForDeletion()
        }

        verify {
            shortLinkRepository.findByDeleteAfterIsNotNull()
        }
    }
}